// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dc.Proto.Common {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SD2RjLnByb3RvLmNvbW1vbiI2CghFbmRwb2ludBIM",
            "CgRob3N0GAEgASgJEgwKBHBvcnQYAiABKA0SDgoGcmVnaW9uGAMgASgJIrAC",
            "Cg5Xb3JsZEVudHJ5Tm9kZRIQCgh3b3JsZF9pZBgBIAEoDRITCgtzZXJ2ZXJf",
            "Y29kZRgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSDgoGcmVnaW9uGAQg",
            "ASgJEi4KBnN0YXR1cxgFIAEoDjIeLmRjLnByb3RvLmNvbW1vbi5TZXJ2aWNl",
            "U3RhdHVzEhMKC3JlY29tbWVuZGVkGAYgASgIEhIKCnBvcHVsYXRpb24YByAB",
            "KA0SEAoIY2FwYWNpdHkYCCABKA0SOAoPdHJhbnNmZXJfcG9saWN5GAkgASgO",
            "Mh8uZGMucHJvdG8uY29tbW9uLlRyYW5zZmVyUG9saWN5EiwKCWVuZHBvaW50",
            "cxgKIAMoCzIZLmRjLnByb3RvLmNvbW1vbi5FbmRwb2ludCpyCg9QYWNrZXRS",
            "b3V0ZUtpbmQSIQodUEFDS0VUX1JPVVRFX0tJTkRfVU5TUEVDSUZJRUQQABIc",
            "ChhQQUNLRVRfUk9VVEVfS0lORF9DTElFTlQQARIeChpQQUNLRVRfUk9VVEVf",
            "S0lORF9JTlRFUk5BTBACKrEBCg1TZXJ2aWNlU3RhdHVzEh4KGlNFUlZJQ0Vf",
            "U1RBVFVTX1VOU1BFQ0lGSUVEEAASFQoRU0VSVklDRV9TVEFUVVNfVVAQARIX",
            "ChNTRVJWSUNFX1NUQVRVU19CVVNZEAISFwoTU0VSVklDRV9TVEFUVVNfRlVM",
            "TBADEhcKE1NFUlZJQ0VfU1RBVFVTX0RPV04QBBIeChpTRVJWSUNFX1NUQVRV",
            "U19NQUlOVEVOQU5DRRAFKnQKDlRyYW5zZmVyUG9saWN5Eh8KG1RSQU5TRkVS",
            "X1BPTElDWV9VTlNQRUNJRklFRBAAEiAKHFRSQU5TRkVSX1BPTElDWV9ESVJF",
            "Q1RfV09STEQQARIfChtUUkFOU0ZFUl9QT0xJQ1lfV09STERfRlJPTlQQAiq4",
            "AQoSWm9uZU1hcFN0YXRlUmVhc29uEicKI1pPTkVfTUFQX1NUQVRFX1JFQVNP",
            "Tl9FTlRFUl9TVUNDRVNTEAASKQolWk9ORV9NQVBfU1RBVEVfUkVBU09OX1BP",
            "U0lUSU9OX1VQREFURRABEiYKIlpPTkVfTUFQX1NUQVRFX1JFQVNPTl9aT05F",
            "X0NIQU5HRUQQAhImCiJaT05FX01BUF9TVEFURV9SRUFTT05fUE9SVEFMX01P",
            "VkVEEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dc.Proto.Common.PacketRouteKind), typeof(global::Dc.Proto.Common.ServiceStatus), typeof(global::Dc.Proto.Common.TransferPolicy), typeof(global::Dc.Proto.Common.ZoneMapStateReason), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dc.Proto.Common.Endpoint), global::Dc.Proto.Common.Endpoint.Parser, new[]{ "Host", "Port", "Region" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dc.Proto.Common.WorldEntryNode), global::Dc.Proto.Common.WorldEntryNode.Parser, new[]{ "WorldId", "ServerCode", "DisplayName", "Region", "Status", "Recommended", "Population", "Capacity", "TransferPolicy", "Endpoints" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PacketRouteKind {
    [pbr::OriginalName("PACKET_ROUTE_KIND_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PACKET_ROUTE_KIND_CLIENT")] Client = 1,
    [pbr::OriginalName("PACKET_ROUTE_KIND_INTERNAL")] Internal = 2,
  }

  public enum ServiceStatus {
    [pbr::OriginalName("SERVICE_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("SERVICE_STATUS_UP")] Up = 1,
    [pbr::OriginalName("SERVICE_STATUS_BUSY")] Busy = 2,
    [pbr::OriginalName("SERVICE_STATUS_FULL")] Full = 3,
    [pbr::OriginalName("SERVICE_STATUS_DOWN")] Down = 4,
    [pbr::OriginalName("SERVICE_STATUS_MAINTENANCE")] Maintenance = 5,
  }

  public enum TransferPolicy {
    [pbr::OriginalName("TRANSFER_POLICY_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("TRANSFER_POLICY_DIRECT_WORLD")] DirectWorld = 1,
    [pbr::OriginalName("TRANSFER_POLICY_WORLD_FRONT")] WorldFront = 2,
  }

  public enum ZoneMapStateReason {
    [pbr::OriginalName("ZONE_MAP_STATE_REASON_ENTER_SUCCESS")] EnterSuccess = 0,
    [pbr::OriginalName("ZONE_MAP_STATE_REASON_POSITION_UPDATE")] PositionUpdate = 1,
    [pbr::OriginalName("ZONE_MAP_STATE_REASON_ZONE_CHANGED")] ZoneChanged = 2,
    [pbr::OriginalName("ZONE_MAP_STATE_REASON_PORTAL_MOVED")] PortalMoved = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Endpoint : pb::IMessage<Endpoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Endpoint> _parser = new pb::MessageParser<Endpoint>(() => new Endpoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Endpoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dc.Proto.Common.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint(Endpoint other) : this() {
      host_ = other.host_;
      port_ = other.port_;
      region_ = other.region_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Endpoint Clone() {
      return new Endpoint(this);
    }

    /// <summary>Field number for the "host" field.</summary>
    public const int HostFieldNumber = 1;
    private string host_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Host {
      get { return host_; }
      set {
        host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 2;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "region" field.</summary>
    public const int RegionFieldNumber = 3;
    private string region_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Region {
      get { return region_; }
      set {
        region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Endpoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Endpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Host != other.Host) return false;
      if (Port != other.Port) return false;
      if (Region != other.Region) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Host.Length != 0) hash ^= Host.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (Region.Length != 0) hash ^= Region.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Host.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Host);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Port);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Region);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Host.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Host);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Port);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Region);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Host.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (Region.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Endpoint other) {
      if (other == null) {
        return;
      }
      if (other.Host.Length != 0) {
        Host = other.Host;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.Region.Length != 0) {
        Region = other.Region;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Host = input.ReadString();
            break;
          }
          case 16: {
            Port = input.ReadUInt32();
            break;
          }
          case 26: {
            Region = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Host = input.ReadString();
            break;
          }
          case 16: {
            Port = input.ReadUInt32();
            break;
          }
          case 26: {
            Region = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldEntryNode : pb::IMessage<WorldEntryNode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldEntryNode> _parser = new pb::MessageParser<WorldEntryNode>(() => new WorldEntryNode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldEntryNode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dc.Proto.Common.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldEntryNode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldEntryNode(WorldEntryNode other) : this() {
      worldId_ = other.worldId_;
      serverCode_ = other.serverCode_;
      displayName_ = other.displayName_;
      region_ = other.region_;
      status_ = other.status_;
      recommended_ = other.recommended_;
      population_ = other.population_;
      capacity_ = other.capacity_;
      transferPolicy_ = other.transferPolicy_;
      endpoints_ = other.endpoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldEntryNode Clone() {
      return new WorldEntryNode(this);
    }

    /// <summary>Field number for the "world_id" field.</summary>
    public const int WorldIdFieldNumber = 1;
    private uint worldId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "server_code" field.</summary>
    public const int ServerCodeFieldNumber = 2;
    private string serverCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerCode {
      get { return serverCode_; }
      set {
        serverCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 3;
    private string displayName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "region" field.</summary>
    public const int RegionFieldNumber = 4;
    private string region_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Region {
      get { return region_; }
      set {
        region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 5;
    private global::Dc.Proto.Common.ServiceStatus status_ = global::Dc.Proto.Common.ServiceStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dc.Proto.Common.ServiceStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "recommended" field.</summary>
    public const int RecommendedFieldNumber = 6;
    private bool recommended_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Recommended {
      get { return recommended_; }
      set {
        recommended_ = value;
      }
    }

    /// <summary>Field number for the "population" field.</summary>
    public const int PopulationFieldNumber = 7;
    private uint population_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Population {
      get { return population_; }
      set {
        population_ = value;
      }
    }

    /// <summary>Field number for the "capacity" field.</summary>
    public const int CapacityFieldNumber = 8;
    private uint capacity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Capacity {
      get { return capacity_; }
      set {
        capacity_ = value;
      }
    }

    /// <summary>Field number for the "transfer_policy" field.</summary>
    public const int TransferPolicyFieldNumber = 9;
    private global::Dc.Proto.Common.TransferPolicy transferPolicy_ = global::Dc.Proto.Common.TransferPolicy.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dc.Proto.Common.TransferPolicy TransferPolicy {
      get { return transferPolicy_; }
      set {
        transferPolicy_ = value;
      }
    }

    /// <summary>Field number for the "endpoints" field.</summary>
    public const int EndpointsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Dc.Proto.Common.Endpoint> _repeated_endpoints_codec
        = pb::FieldCodec.ForMessage(82, global::Dc.Proto.Common.Endpoint.Parser);
    private readonly pbc::RepeatedField<global::Dc.Proto.Common.Endpoint> endpoints_ = new pbc::RepeatedField<global::Dc.Proto.Common.Endpoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dc.Proto.Common.Endpoint> Endpoints {
      get { return endpoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldEntryNode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldEntryNode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorldId != other.WorldId) return false;
      if (ServerCode != other.ServerCode) return false;
      if (DisplayName != other.DisplayName) return false;
      if (Region != other.Region) return false;
      if (Status != other.Status) return false;
      if (Recommended != other.Recommended) return false;
      if (Population != other.Population) return false;
      if (Capacity != other.Capacity) return false;
      if (TransferPolicy != other.TransferPolicy) return false;
      if(!endpoints_.Equals(other.endpoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorldId != 0) hash ^= WorldId.GetHashCode();
      if (ServerCode.Length != 0) hash ^= ServerCode.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (Region.Length != 0) hash ^= Region.GetHashCode();
      if (Status != global::Dc.Proto.Common.ServiceStatus.Unspecified) hash ^= Status.GetHashCode();
      if (Recommended != false) hash ^= Recommended.GetHashCode();
      if (Population != 0) hash ^= Population.GetHashCode();
      if (Capacity != 0) hash ^= Capacity.GetHashCode();
      if (TransferPolicy != global::Dc.Proto.Common.TransferPolicy.Unspecified) hash ^= TransferPolicy.GetHashCode();
      hash ^= endpoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorldId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(WorldId);
      }
      if (ServerCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServerCode);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Region);
      }
      if (Status != global::Dc.Proto.Common.ServiceStatus.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Status);
      }
      if (Recommended != false) {
        output.WriteRawTag(48);
        output.WriteBool(Recommended);
      }
      if (Population != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Population);
      }
      if (Capacity != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Capacity);
      }
      if (TransferPolicy != global::Dc.Proto.Common.TransferPolicy.Unspecified) {
        output.WriteRawTag(72);
        output.WriteEnum((int) TransferPolicy);
      }
      endpoints_.WriteTo(output, _repeated_endpoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorldId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(WorldId);
      }
      if (ServerCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServerCode);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Region);
      }
      if (Status != global::Dc.Proto.Common.ServiceStatus.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Status);
      }
      if (Recommended != false) {
        output.WriteRawTag(48);
        output.WriteBool(Recommended);
      }
      if (Population != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Population);
      }
      if (Capacity != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Capacity);
      }
      if (TransferPolicy != global::Dc.Proto.Common.TransferPolicy.Unspecified) {
        output.WriteRawTag(72);
        output.WriteEnum((int) TransferPolicy);
      }
      endpoints_.WriteTo(ref output, _repeated_endpoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorldId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WorldId);
      }
      if (ServerCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerCode);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (Region.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
      }
      if (Status != global::Dc.Proto.Common.ServiceStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Recommended != false) {
        size += 1 + 1;
      }
      if (Population != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Population);
      }
      if (Capacity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Capacity);
      }
      if (TransferPolicy != global::Dc.Proto.Common.TransferPolicy.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TransferPolicy);
      }
      size += endpoints_.CalculateSize(_repeated_endpoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldEntryNode other) {
      if (other == null) {
        return;
      }
      if (other.WorldId != 0) {
        WorldId = other.WorldId;
      }
      if (other.ServerCode.Length != 0) {
        ServerCode = other.ServerCode;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.Region.Length != 0) {
        Region = other.Region;
      }
      if (other.Status != global::Dc.Proto.Common.ServiceStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.Recommended != false) {
        Recommended = other.Recommended;
      }
      if (other.Population != 0) {
        Population = other.Population;
      }
      if (other.Capacity != 0) {
        Capacity = other.Capacity;
      }
      if (other.TransferPolicy != global::Dc.Proto.Common.TransferPolicy.Unspecified) {
        TransferPolicy = other.TransferPolicy;
      }
      endpoints_.Add(other.endpoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WorldId = input.ReadUInt32();
            break;
          }
          case 18: {
            ServerCode = input.ReadString();
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            Region = input.ReadString();
            break;
          }
          case 40: {
            Status = (global::Dc.Proto.Common.ServiceStatus) input.ReadEnum();
            break;
          }
          case 48: {
            Recommended = input.ReadBool();
            break;
          }
          case 56: {
            Population = input.ReadUInt32();
            break;
          }
          case 64: {
            Capacity = input.ReadUInt32();
            break;
          }
          case 72: {
            TransferPolicy = (global::Dc.Proto.Common.TransferPolicy) input.ReadEnum();
            break;
          }
          case 82: {
            endpoints_.AddEntriesFrom(input, _repeated_endpoints_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WorldId = input.ReadUInt32();
            break;
          }
          case 18: {
            ServerCode = input.ReadString();
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            Region = input.ReadString();
            break;
          }
          case 40: {
            Status = (global::Dc.Proto.Common.ServiceStatus) input.ReadEnum();
            break;
          }
          case 48: {
            Recommended = input.ReadBool();
            break;
          }
          case 56: {
            Population = input.ReadUInt32();
            break;
          }
          case 64: {
            Capacity = input.ReadUInt32();
            break;
          }
          case 72: {
            TransferPolicy = (global::Dc.Proto.Common.TransferPolicy) input.ReadEnum();
            break;
          }
          case 82: {
            endpoints_.AddEntriesFrom(ref input, _repeated_endpoints_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
