// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: internal_login_account.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dc.Proto.Internal.LoginAccount {

  /// <summary>Holder for reflection information generated from internal_login_account.proto</summary>
  public static partial class InternalLoginAccountReflection {

    #region Descriptor
    /// <summary>File descriptor for internal_login_account.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InternalLoginAccountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxpbnRlcm5hbF9sb2dpbl9hY2NvdW50LnByb3RvEh9kYy5wcm90by5pbnRl",
            "cm5hbC5sb2dpbl9hY2NvdW50Ggxjb21tb24ucHJvdG8ikAEKCkF1dGhSZXN1",
            "bHQSCgoCb2sYASABKAgSEgoKYWNjb3VudF9pZBgCIAEoBBIVCg1sb2dpbl9z",
            "ZXNzaW9uGAMgASgJEjYKDXdvcmxkX2VudHJpZXMYBCADKAsyHy5kYy5wcm90",
            "by5jb21tb24uV29ybGRFbnRyeU5vZGUSEwoLZmFpbF9yZWFzb24YBSABKAki",
            "YwoQV29ybGRMaXN0UmVxdWVzdBIQCgh0cmFjZV9pZBgBIAEoBBISCgpyZXF1",
            "ZXN0X2lkGAIgASgEEhIKCmFjY291bnRfaWQYAyABKAQSFQoNbG9naW5fc2Vz",
            "c2lvbhgEIAEoCSKSAQoRV29ybGRMaXN0UmVzcG9uc2USEAoIdHJhY2VfaWQY",
            "ASABKAQSEgoKcmVxdWVzdF9pZBgCIAEoBBIKCgJvaxgDIAEoCBI2Cg13b3Js",
            "ZF9lbnRyaWVzGAQgAygLMh8uZGMucHJvdG8uY29tbW9uLldvcmxkRW50cnlO",
            "b2RlEhMKC2ZhaWxfcmVhc29uGAUgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dc.Proto.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dc.Proto.Internal.LoginAccount.AuthResult), global::Dc.Proto.Internal.LoginAccount.AuthResult.Parser, new[]{ "Ok", "AccountId", "LoginSession", "WorldEntries", "FailReason" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dc.Proto.Internal.LoginAccount.WorldListRequest), global::Dc.Proto.Internal.LoginAccount.WorldListRequest.Parser, new[]{ "TraceId", "RequestId", "AccountId", "LoginSession" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dc.Proto.Internal.LoginAccount.WorldListResponse), global::Dc.Proto.Internal.LoginAccount.WorldListResponse.Parser, new[]{ "TraceId", "RequestId", "Ok", "WorldEntries", "FailReason" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AuthResult : pb::IMessage<AuthResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthResult> _parser = new pb::MessageParser<AuthResult>(() => new AuthResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dc.Proto.Internal.LoginAccount.InternalLoginAccountReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthResult(AuthResult other) : this() {
      ok_ = other.ok_;
      accountId_ = other.accountId_;
      loginSession_ = other.loginSession_;
      worldEntries_ = other.worldEntries_.Clone();
      failReason_ = other.failReason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthResult Clone() {
      return new AuthResult(this);
    }

    /// <summary>Field number for the "ok" field.</summary>
    public const int OkFieldNumber = 1;
    private bool ok_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ok {
      get { return ok_; }
      set {
        ok_ = value;
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private ulong accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "login_session" field.</summary>
    public const int LoginSessionFieldNumber = 3;
    private string loginSession_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginSession {
      get { return loginSession_; }
      set {
        loginSession_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "world_entries" field.</summary>
    public const int WorldEntriesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Dc.Proto.Common.WorldEntryNode> _repeated_worldEntries_codec
        = pb::FieldCodec.ForMessage(34, global::Dc.Proto.Common.WorldEntryNode.Parser);
    private readonly pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode> worldEntries_ = new pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode> WorldEntries {
      get { return worldEntries_; }
    }

    /// <summary>Field number for the "fail_reason" field.</summary>
    public const int FailReasonFieldNumber = 5;
    private string failReason_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FailReason {
      get { return failReason_; }
      set {
        failReason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ok != other.Ok) return false;
      if (AccountId != other.AccountId) return false;
      if (LoginSession != other.LoginSession) return false;
      if(!worldEntries_.Equals(other.worldEntries_)) return false;
      if (FailReason != other.FailReason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ok != false) hash ^= Ok.GetHashCode();
      if (AccountId != 0UL) hash ^= AccountId.GetHashCode();
      if (LoginSession.Length != 0) hash ^= LoginSession.GetHashCode();
      hash ^= worldEntries_.GetHashCode();
      if (FailReason.Length != 0) hash ^= FailReason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ok != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ok);
      }
      if (AccountId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(AccountId);
      }
      if (LoginSession.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LoginSession);
      }
      worldEntries_.WriteTo(output, _repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FailReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ok != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ok);
      }
      if (AccountId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(AccountId);
      }
      if (LoginSession.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LoginSession);
      }
      worldEntries_.WriteTo(ref output, _repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FailReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ok != false) {
        size += 1 + 1;
      }
      if (AccountId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AccountId);
      }
      if (LoginSession.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginSession);
      }
      size += worldEntries_.CalculateSize(_repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FailReason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthResult other) {
      if (other == null) {
        return;
      }
      if (other.Ok != false) {
        Ok = other.Ok;
      }
      if (other.AccountId != 0UL) {
        AccountId = other.AccountId;
      }
      if (other.LoginSession.Length != 0) {
        LoginSession = other.LoginSession;
      }
      worldEntries_.Add(other.worldEntries_);
      if (other.FailReason.Length != 0) {
        FailReason = other.FailReason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Ok = input.ReadBool();
            break;
          }
          case 16: {
            AccountId = input.ReadUInt64();
            break;
          }
          case 26: {
            LoginSession = input.ReadString();
            break;
          }
          case 34: {
            worldEntries_.AddEntriesFrom(input, _repeated_worldEntries_codec);
            break;
          }
          case 42: {
            FailReason = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Ok = input.ReadBool();
            break;
          }
          case 16: {
            AccountId = input.ReadUInt64();
            break;
          }
          case 26: {
            LoginSession = input.ReadString();
            break;
          }
          case 34: {
            worldEntries_.AddEntriesFrom(ref input, _repeated_worldEntries_codec);
            break;
          }
          case 42: {
            FailReason = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldListRequest : pb::IMessage<WorldListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldListRequest> _parser = new pb::MessageParser<WorldListRequest>(() => new WorldListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dc.Proto.Internal.LoginAccount.InternalLoginAccountReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListRequest(WorldListRequest other) : this() {
      traceId_ = other.traceId_;
      requestId_ = other.requestId_;
      accountId_ = other.accountId_;
      loginSession_ = other.loginSession_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListRequest Clone() {
      return new WorldListRequest(this);
    }

    /// <summary>Field number for the "trace_id" field.</summary>
    public const int TraceIdFieldNumber = 1;
    private ulong traceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TraceId {
      get { return traceId_; }
      set {
        traceId_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private ulong requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 3;
    private ulong accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "login_session" field.</summary>
    public const int LoginSessionFieldNumber = 4;
    private string loginSession_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginSession {
      get { return loginSession_; }
      set {
        loginSession_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TraceId != other.TraceId) return false;
      if (RequestId != other.RequestId) return false;
      if (AccountId != other.AccountId) return false;
      if (LoginSession != other.LoginSession) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TraceId != 0UL) hash ^= TraceId.GetHashCode();
      if (RequestId != 0UL) hash ^= RequestId.GetHashCode();
      if (AccountId != 0UL) hash ^= AccountId.GetHashCode();
      if (LoginSession.Length != 0) hash ^= LoginSession.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TraceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TraceId);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (AccountId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(AccountId);
      }
      if (LoginSession.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LoginSession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TraceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TraceId);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (AccountId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(AccountId);
      }
      if (LoginSession.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LoginSession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TraceId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TraceId);
      }
      if (RequestId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestId);
      }
      if (AccountId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AccountId);
      }
      if (LoginSession.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginSession);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldListRequest other) {
      if (other == null) {
        return;
      }
      if (other.TraceId != 0UL) {
        TraceId = other.TraceId;
      }
      if (other.RequestId != 0UL) {
        RequestId = other.RequestId;
      }
      if (other.AccountId != 0UL) {
        AccountId = other.AccountId;
      }
      if (other.LoginSession.Length != 0) {
        LoginSession = other.LoginSession;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TraceId = input.ReadUInt64();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 24: {
            AccountId = input.ReadUInt64();
            break;
          }
          case 34: {
            LoginSession = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TraceId = input.ReadUInt64();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 24: {
            AccountId = input.ReadUInt64();
            break;
          }
          case 34: {
            LoginSession = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldListResponse : pb::IMessage<WorldListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldListResponse> _parser = new pb::MessageParser<WorldListResponse>(() => new WorldListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dc.Proto.Internal.LoginAccount.InternalLoginAccountReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListResponse(WorldListResponse other) : this() {
      traceId_ = other.traceId_;
      requestId_ = other.requestId_;
      ok_ = other.ok_;
      worldEntries_ = other.worldEntries_.Clone();
      failReason_ = other.failReason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldListResponse Clone() {
      return new WorldListResponse(this);
    }

    /// <summary>Field number for the "trace_id" field.</summary>
    public const int TraceIdFieldNumber = 1;
    private ulong traceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TraceId {
      get { return traceId_; }
      set {
        traceId_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private ulong requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "ok" field.</summary>
    public const int OkFieldNumber = 3;
    private bool ok_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ok {
      get { return ok_; }
      set {
        ok_ = value;
      }
    }

    /// <summary>Field number for the "world_entries" field.</summary>
    public const int WorldEntriesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Dc.Proto.Common.WorldEntryNode> _repeated_worldEntries_codec
        = pb::FieldCodec.ForMessage(34, global::Dc.Proto.Common.WorldEntryNode.Parser);
    private readonly pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode> worldEntries_ = new pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Dc.Proto.Common.WorldEntryNode> WorldEntries {
      get { return worldEntries_; }
    }

    /// <summary>Field number for the "fail_reason" field.</summary>
    public const int FailReasonFieldNumber = 5;
    private string failReason_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FailReason {
      get { return failReason_; }
      set {
        failReason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TraceId != other.TraceId) return false;
      if (RequestId != other.RequestId) return false;
      if (Ok != other.Ok) return false;
      if(!worldEntries_.Equals(other.worldEntries_)) return false;
      if (FailReason != other.FailReason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TraceId != 0UL) hash ^= TraceId.GetHashCode();
      if (RequestId != 0UL) hash ^= RequestId.GetHashCode();
      if (Ok != false) hash ^= Ok.GetHashCode();
      hash ^= worldEntries_.GetHashCode();
      if (FailReason.Length != 0) hash ^= FailReason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TraceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TraceId);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (Ok != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ok);
      }
      worldEntries_.WriteTo(output, _repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FailReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TraceId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TraceId);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (Ok != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ok);
      }
      worldEntries_.WriteTo(ref output, _repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FailReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TraceId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TraceId);
      }
      if (RequestId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestId);
      }
      if (Ok != false) {
        size += 1 + 1;
      }
      size += worldEntries_.CalculateSize(_repeated_worldEntries_codec);
      if (FailReason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FailReason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldListResponse other) {
      if (other == null) {
        return;
      }
      if (other.TraceId != 0UL) {
        TraceId = other.TraceId;
      }
      if (other.RequestId != 0UL) {
        RequestId = other.RequestId;
      }
      if (other.Ok != false) {
        Ok = other.Ok;
      }
      worldEntries_.Add(other.worldEntries_);
      if (other.FailReason.Length != 0) {
        FailReason = other.FailReason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TraceId = input.ReadUInt64();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 24: {
            Ok = input.ReadBool();
            break;
          }
          case 34: {
            worldEntries_.AddEntriesFrom(input, _repeated_worldEntries_codec);
            break;
          }
          case 42: {
            FailReason = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TraceId = input.ReadUInt64();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 24: {
            Ok = input.ReadBool();
            break;
          }
          case 34: {
            worldEntries_.AddEntriesFrom(ref input, _repeated_worldEntries_codec);
            break;
          }
          case 42: {
            FailReason = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
